#!/bin/bash
# Update standard packages to the backports version.

if $use_backports_packages; then
log 'Install Backports Packages'
chroot $imagedir apt-get -t ${codename}-backports -y install ${backports_packages}
fi
