#!/bin/bash
# Bootstrap

# Concatenate the packages
SAVE_IFS=$IFS
IFS=","
include="${packages[*]}"
exclude="${exclude_packages[*]}"
IFS=$SAVE_IFS
keep_debootstrap_dir=""

# If backports packages applied files, don't wipe the target directory, otherwise the
# backports won't be selected.
if $use_backports_packages; then
  keep_debootstrap_dir="--keep-debootstrap-dir"
fi

# For bootstrapping purposes, we just use the first-listed mirror even if
# multiple are specified.
bootstrap_mirror=${apt_mirrors%% *}

bootstrap_args="--arch $arch --include=$include --exclude=$exclude
$codename $imagedir $bootstrap_mirror"

args_hash=`printf -- "$arch $include -- $exclude $codename" | sha1sum`

tarball="$tarballdir/bootstrap-${args_hash:0:7}.tar"

include_param=""
if [[ $include != "" ]]; then
	include_param="--include=$include"
fi

exclude_param=""
if [[ $exclude != "" ]]; then
	exclude_param="--exclude=$exclude"
fi

# When testing, some bootstraps can fail, instead of re-downloading it all
# we create a tarball containing all the necessary things for bootstrapping
if [ ! -e "$tarball" ]; then
	log "Creating the bootstrap tarball"
	debootstrap --arch $arch --make-tarball=$tarball \
		${include_param} ${exclude_param} \
		$codename $imagedir $bootstrap_mirror $keep_debootstrap_dir | spin
	[ $PIPESTATUS == 1 ] || die "Creating bootstrap tarball failed!"
fi

log "Bootstrapping"
debootstrap --arch $arch --unpack-tarball=$tarball \
	${include_param} ${exclude_param} \
	$codename $imagedir $bootstrap_mirror | spin
[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
