#!/bin/bash
set -e

# https://github.com/dotcloud/docker/blob/master/contrib/init/sysvinit-debian/docker
init_scripts+=("$scriptdir/plugins/install-docker-tasks/files/init.d/docker")
# https://github.com/dotcloud/docker/blob/master/contrib/init/sysvinit-debian/docker.default
cp "$scriptdir/plugins/install-docker-tasks/files/default/docker" "$imagedir/etc/default/docker"
